Repository weechat/weechat.org, pull requests merged in 2019-03, with the labels that each got.

#92 Add Haiku as supported platform
  media/images/ft_os.png
  weechat/locale/fr/LC_MESSAGES/django.po
  weechat/locale/it/LC_MESSAGES/django.po
  weechat/locale/ja/LC_MESSAGES/django.po
  weechat/locale/pl/LC_MESSAGES/django.po
  weechat/locale/pt_BR/LC_MESSAGES/django.po
  weechat/templates/about/features.html
Labels: enhancement

#93 Fix missing ADMIN_PAGE in installation
  weechat/settings_local.template
Labels: bug

#94 Update Japanese translations
  weechat/locale/ja/LC_MESSAGES/django.po
Labels: translations
